name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
      - uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Update version and publish
        run: |
          git config --global user.email "github@action.com"
          git config --global user.name "Github Action"
      - uses: borales/actions-yarn@v5
        name: Publish package on NPM
        with:
          cmd: publish --non-interactive --new-version ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
