name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint_typecheck_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
      - uses: borales/actions-yarn@v5
        with:
          cmd: build
      - uses: borales/actions-yarn@v5
        with:
          cmd: test
      - uses: borales/actions-yarn@v5
        with:
          cmd: lint
      - uses: borales/actions-yarn@v5
        with:
          cmd: type-check
