name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint_typecheck_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
      - uses: borales/actions-yarn@v5
        with:
          cmd: build
      - uses: borales/actions-yarn@v5
        with:
          cmd: test
      - uses: borales/actions-yarn@v5
        with:
          cmd: lint
      - uses: borales/actions-yarn@v5
        with:
          cmd: type-check

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
      - uses: borales/actions-yarn@v5
        with:
          cmd: build
      - uses: borales/actions-yarn@v5
        name: Publish package on NPM
        with:
          cmd: publish --non-interactive --new-version ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_prerelease:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: borales/actions-yarn@v5
        with:
          cmd: install
      - uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Set git config
        run: |
          git fetch --tags
          echo "TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)" | tee -a $GITHUB_ENV
      - uses: borales/actions-yarn@v5
        name: Publish package on NPM
        with:
          cmd: publish --no-git-tag-version --non-interactive --tag next --new-version ${{ env.TAG }}-next-${{ github.run_id }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
